[package]
name = "teos-common"
version = "0.0.1"
authors = ["Sergi Delgado Segura <sergi.delgado.s@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.126", features = ["derive"]}
serde_json = "1.0"
uuid = { version = "0.8", features = ["serde", "v4"] }
hex = "0.4.3"

chacha20poly1305 = "0.8.0"

bitcoin = "0.26"
lightning = "0.0.98"
